# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e51677f8bbe69621fd1e091c2327f6221fe23073caeb67bf1081b6b11906561b61a9a544753fe99f1f5203551ce8aecf570cbe0fa9807b2cc0b28a3cddd4e8f9

test:
  secret_key_base: d8b1038464d247e8b9b23757f435c925a4e506e72f3972fb28a25c8bd1a3a041d5dea3de62fa47d3bd082c3e33dfb817b443fd731318bd25f12bef7d7ee73653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
